EMPLOYEE_CLASS = ((1, 'Nombramiento'),(2, 'Contratado'),(3, 'Jubilado'),)
TYPE_DISCOUNT = ((1, 'Ninguno'),(2, 'Prestamo'),(3, 'Seguro'),(4, 'Descuento varios'),(5, 'Multas'))
TYPE_ITEM = ((1, 'Ingreso'),(2, 'Descuento'),(3, 'Calculo'))
FREQUENCY_ROL = ((1, 'Mensual'),(2, 'Quincenal'),(3, 'Semanal'))
CLASS_PERMISSION = ((1, 'Calamidad Domestica'),(2, 'Injustificado'),(3, 'Enfermedad'),(4, 'Enfermedad Regenerativa'),(5, 'Accidente'),(6, 'Maternidad'),(7, 'Paternidad'),(8, 'Vacacion'))
TIME_DESCUENT = ((1,"dias"),(2,"Horas"))